package com.example.itantra.ui.theme

import androidx.compose.ui.graphics.Color

// ── Neural Tactical Interface — Stitch Design System ─────────────────────────
// Generated by Google Stitch for iTantra Neural Walkie-Talkie
// Design ID: projects/13078437623162040590 / Screen: be6f7d2bdc68424e95efcaf86271c289

// ── Base surfaces ─────────────────────────────────────────────────────────────
val Background               = Color(0xFF11131B)   // Level 0 — deep navy
val SurfaceContainerLowest   = Color(0xFF0C0E16)   // Deepest pit
val SurfaceContainerLow      = Color(0xFF191B24)   // Level 1 cards
val SurfaceContainer         = Color(0xFF1D1F28)   // Level 2 — standard card
val SurfaceContainerHigh     = Color(0xFF282A32)   // Level 3
val SurfaceContainerHighest  = Color(0xFF33343E)   // Highest elevation
val SurfaceBright            = Color(0xFF373942)   // Brightest surface

// ── Accent — Primary (Neon Green) ────────────────────────────────────────────
val Primary                  = Color(0xFF4ADE80)   // Vibrant green accent
val PrimaryBright            = Color(0xFF6BFB9A)   // Extra bright
val PrimaryFixed             = Color(0xFF6DFE9C)
val PrimaryFixedDim          = Color(0xFF4DE082)
val PrimaryContainer         = Color(0xFF4ADE80)
val OnPrimary                = Color(0xFF003919)
val OnPrimaryContainer       = Color(0xFF005E2D)
val GreenGlow                = Color(0x334ADE80)   // 20% opacity glow
val GreenGlowBright          = Color(0x664ADE80)   // 40% opacity — active

// ── Secondary ────────────────────────────────────────────────────────────────
val Secondary                = Color(0xFFC4C5D6)
val SecondaryContainer       = Color(0xFF434654)
val OnSecondary              = Color(0xFF2D303D)
val OnSecondaryContainer     = Color(0xFFB2B4C4)

// ── Tertiary (Alert / Emergency) ─────────────────────────────────────────────
val Tertiary                 = Color(0xFFFFD7D3)
val TertiaryContainer        = Color(0xFFFFB0AA)
val OnTertiary               = Color(0xFF68000A)
val OnTertiaryContainer      = Color(0xFFA50318)
val AlertRed                 = Color(0xFFEF4444)
val AlertRedGlow             = Color(0x33EF4444)   // 20% opacity glow
val AlertRedDim              = Color(0x1AEF4444)   // 10% for background

// ── Status chips ─────────────────────────────────────────────────────────────
val ChipConnected            = Color(0xFF4ADE80)
val ChipSearching            = Color(0xFFFBBF24)   // Amber
val ChipOffline              = Color(0xFF6B7280)

// ── Error ────────────────────────────────────────────────────────────────────
val Error                    = Color(0xFFFFB4AB)
val ErrorContainer           = Color(0xFF93000A)
val OnError                  = Color(0xFF690005)
val OnErrorContainer         = Color(0xFFFFDAD6)

// ── Text ─────────────────────────────────────────────────────────────────────
val OnBackground             = Color(0xFFE2E1EE)
val OnSurface                = Color(0xFFE2E1EE)
val OnSurfaceVariant         = Color(0xFFBCCABB)
val Outline                  = Color(0xFF869486)
val OutlineVariant           = Color(0xFF3D4A3E)

// ── Structural ───────────────────────────────────────────────────────────────
val CardBorder               = Color(0xFF2D3245)   // 1px inner stroke on cards
val Scrim                    = Color(0xCC000000)